### ISSUE TITLE
A warm welcome to all the beginner contributes

### ISSUE THREAD

**Issue by Glitchyi** [GDSC-MITS/Contribute-To-HacktoberFest#1]
Register anytime between September 26 and October 31

    Pull requests can be made in any [GitHub](https://github.com/topics/hacktoberfest) or [GitLab](https://gitlab.com/explore/projects/topics/hacktoberfest) hosted project that’s participating in Hacktoberfest (look for the “hacktoberfest” topic)

    Project maintainers must accept your pull/merge requests for them to count toward your total

    Have 4 pull/merge requests accepted between October 1 and October 31 to complete Hacktoberfest

    The first 40,000 participants (maintainers and contributors) who complete Hacktoberfest can elect to receive one of two prizes: a tree planted in their name, or the Hacktoberfest 2022 t-shirt.

**Comment by kusum-chowdhury** [comment]
How can i contribute? is there any issue i can work on?

**Comment by ShrutiSingh04503** [comment]
Hey, I'll love to work on this issue, Would appreciate it if you assign me.

**Comment by Glitchyi** [comment]
Hey Guys, feel free to contibute something interesting or anything you think that others would feel usefull or some things you feel were usefull, ill be sure to make a few more issues in the coming days

**Comment by SAHILALAWADHI** [comment]
@Glitchyi 
Assign this to me. I would like to work on it

**Comment by Dishu099** [comment]
Hey @Glitchyi can I contribute in your repo
