### ISSUE TITLE
Want to add Armstrong program as it is beginner friendly and interesting

### ISSUE THREAD

**Issue by kfayazuddin** [GDSC-MITS/Contribute-To-HacktoberFest#21]
Hi 
please i want to add Armstrong number code in java.
Kindly please assign this task for me

**Comment by Arka009chakraborty** [comment]
Bro I have very optimal answer for this question kindly assign me this task

**Comment by Glitchyi** [comment]
Making issues is not required, please feel free to fork this repo and submit a pull request
